language: go
sudo: required
services:
  - docker
go:
  - tip
install: true
before_install:
  - go get -v ./...
script:
  - ./.travis-test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t snagles/docker-registry-manager .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push snagles/docker-registry-manager;
    fi
