version: '2'

services:
  docker-registry-manager:
    container_name: docker-registry-manager
    image: snagles/docker-registry-manager
    ports:
      - "8080:8080"
    environment:
    # - MANAGER_REGISTRIES=http://localhost:5000,https://example.com:5000,http://testuser:testpassword@localhost:5000
      - MANAGER_LOG_LEVEL=5
      - MANAGER_REFRESH_RATE=1m
    #  - MANAGER_SKIP_TLS=true
