#!/bin/bash

sed -i "s#PEGASUS_AWX_DOCKER_REGISTRY_AUTH_SECRETS_JINJA2_VAR#$PEGASUS_AWX_DOCKER_REGISTRY_AUTH_SECRETS#g" ./.env
sed -i "s#PEGASUS_AWX_DOCKER_REGISTRY_TLS_SECRETS_JINJA2_VAR#$PEGASUS_AWX_DOCKER_REGISTRY_TLS_SECRETS#g" ./.env
sed -i "s#PEGASUS_CERTBOT_PATH_INSIDER_JINJA2_VAR#$PEGASUS_CERTBOT_PATH_INSIDER#g" ./.env
